config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
  validates :phone_number, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates_numericality_of :rating, only_integer: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :review)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <div class="form-group">
    <%= f.label :name, "Enter restaurant's name" %><br>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :address, "Enter restaurant's address" %><br>
    <%= f.text_field :address, class: 'form-control' %>

    <%= f.label :phone_number, "Enter restaurant's phone_number" %><br>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category, "Select restaurant's category" %><br>
    <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"] %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit a new restaurant", class: "btn btn-primary" %>
  </div>

<% end %>

<%= link_to "Back to Restaurants", restaurants_path %>

app/views/restaurants/edit.html.erb
<h2>Edit your restaurant</h2>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants Listing</h1>

  <h3><% @restaurants.each do |restaurant| %></h3>
  <h3><%= restaurant.name %></h3>
  <ul>
    <li><%= restaurant.address %></li>
    <li><%= restaurant.phone_number %></li>
    <li><%= restaurant.category %></li>
  </ul>

  <%= link_to 'Show restaurant', restaurant_path(restaurant) %> |
  <%= link_to 'Edit exiting restaurant', edit_restaurant_path(restaurant) %>

  <% end %>

  <%= link_to 'Add a new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h2>Create a new restaurant</h2>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h3><strong>Retaurant's name: </strong><%= @restaurant.name %></h3>

<ul>
  <li><%= @restaurant.address %></li>
  <li><%= @restaurant.phone_number %></li>
  <li><%= @restaurant.category %></li>
</ul>

<h5>Reviews</h5>

<% @restaurant.reviews.each do |review| %>
  <ul>
    <li><%= review.content %></li>
    <li> <%= review.rating %></li>
  </ul>
<% end %>

<h5><%= link_to "Create a review", new_restaurant_review_path(@restaurant) %></h5>

app/views/reviews/_form.html.erb
<h3>Create a new review</h3>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.label :rating %>: <%= f.select :rating, [0, 1, 2, 3, 4, 5]  %>
  <br><br>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form' %>